version: "3"
services:
  mysqldb:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    networks:
      - products
    environment:
      MYSQL_DATABASE: products
      MYSQL_ROOT_PASSWORD: mystore
    volumes:
      - C:/Users/user/Desktop/product:/var/lib/mysql/
  product5:
    build: .
#    image: "mystore-product5:latest"
    restart: always
    ports:
      - "8006:8006"
    networks:
      - products
    environment:
      MYSQL_HOST: mystore-mysqldb-1
#      MYSQL_HOST: mystore-mysqldb-1......when --project-name mystore  is added to docker-compose
      MYSQL_USER: root
      MYSQL_PASSWORD: mystore
    depends_on:
      - mysqldb

networks:
  products:
