server:
  port: 8005

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework: off
